(require 'org)
(org-babel-tangle-file "README.org")
(setq byte-compile-warnings '(not free-vars unresolved noruntime lexical make-local))
(byte-compile-file "README.el")
(byte-compile-file "init.el")
